- eslint.config.js
- src/App.styles.ts
- src/App.tsx
#18 
- eslint 옵션 추가
> Emotion을 사용할 때, JSX에서 css 속성에 대한 에러를 발생시키지 않도록 예외처리할 수 있는 룰을 적용합니다.
- 스타일 파일명 변경
> `App.style.ts` 에서 `App.styles.ts`
> [#18] - Emotion관련 eslint rule추가 및 스타일 기본 파일명 변경

- src/styles/global-styles.ts
close #46 
- global style을 수정하여 브라우저 기본 폰트를 16px에서 10px로 변환하였습니다.
- 폰트 크기를 지정하지 않은 요소는 기본적으로 10px로 적용되므로, 필요한 경우 직접 지정해 주세요!
> [#46] - global style 수정

- package.json
- pnpm-lock.yaml
- src/app.tsx
- src/features/upload/components/file-upload/file-upload.styles.ts
- src/features/upload/components/file-upload/file-upload.tsx
- src/features/upload/upload-page.styles.ts
- src/features/upload/upload-page.tsx
- src/route.tsx
close #43 
- 업로드 페이지 퍼블리싱 작업 진행했습니다. 완성된 디자인이 없어 피그마에 있는 디자인 대로 구현했습니다.
- 업로드 컴포넌트 스타일 적용했습니다.
- 업로드 컴포넌트 기본 기능 구현했습니다. 파일 선택 시 유효한 파일일 경우 바로 react-hook-form의 handleSubmit 함수를 실행합니다. 해당 함수는 추후 업로드 API 호출 기능을 수행할 예정입니다.
- 라우팅 적용했습니다. 현재는
- 랜딩 페이지 (`/`)
- 업로드 페이지 (`/upload`)
- 피드백 페이지 (`/total-evaluation`)
세 가지 경로로 나눠두었습니다.
스타일은 임시로 지정한 거라 크게 확인하지 않아도 됩니다!
> [#43] - 업로드 페이지 퍼블리싱, 업로드 컴포넌트 스타일 적용, 라우팅 기본 적용

- index.html
- src/app.tsx
- src/assets/styles/emotion.d.ts
- src/assets/styles/fonts.ts
- src/assets/styles/global-styles.ts
- src/assets/styles/theme.ts
- src/common/utils/with-theme.ts
close #59
- 기본 폰트 및 타이포그래피 설정  
- Emotion css 리터럴에서 theme을 자동으로 주입하는 유틸 함수 추가  
`with-theme` 파일의 사용법을 참고하여, **css 태그 템플릿을 `withTheme` 함수로 감싸서 사용해 주세요.**  
이를 통해 **theme 타입을 올바르게 추론할 수 있습니다.**
> [#59] - 기본 폰트 및 타이포그래피 설정

- src/common/components/text-input/text-input-status.ts
- src/common/components/text-input/text-input.styles.ts
- src/common/components/text-input/text-input.tsx
- src/common/stories/text-input.stories.tsx
close #68 
- 디자인 시스템 내 TextInput 구현
현재 피그마 디자인 시스템의 TextInput에 타이포그래피와 색상이 적용되어 있지 않아, 우선은 제공된 디자인 그대로 적용하였습니다. 
추후 디자인 시스템이 확정되면 withTheme을 활용해 theme을 적용할 예정입니다.
또한, 현재는 error 상태만 구현되어 있지만, 확장 가능성을 고려하여 status 타입을 분리해 두었습니다.
이를 통해 success, warning 등의 상태를 추가할 수 있으며, 각 상태에 따른 필드 및 메시지 스타일은 `text-input-status.ts`에서 관리할 수 있습니다.
react-hook-form과 zod를 활용한 유효성 검증 예시는 아래와 같습니다.
> [#68] - 디자인 시스템 (Text Input) 구현

- src/common/components/layout/header-buttons/landing-middle-buttons.tsx
- src/features/landing/components/helpers-section/helpers-section.tsx
- src/features/landing/landing-page.tsx
close #125 
- LandingMiddleButton 컴포넌트 내 버튼에 onClick 이벤트를 추가했습니다.
https://github.com/user-attachments/assets/b7d72209-5603-4fff-b0cc-9a586256ba6d
헤더와 랜딩 페이지 요소가 서로 다른 컴포넌트에 있어 ref 대신 id를 사용하여 해당 섹션으로 스크롤 이동하도록 구현했습니다.
> [#125] - 랜딩페이지 헤더 탭 클릭 시 해당 섹션으로 스크롤 이동

- src/common/utils/scroll-to-section.ts
close #144 
헤더 스크롤 인터렉션으로 이동되는 좌표에서 가로 스크롤 부분 포함된 부분을 수정합니다.
1. 가로 스크롤을 위해 진행되는 부분에 특정 좌푯값을 계산하는 로직이 들어있습니다
2. 이를 헤더 스크롤 인터렉션과 결합하기 위해 1번의 로직에 헤더 높이만큼만 뺄셈을 진행했습니다.
> [#144] - 헤더 스크롤 인터렉션 좌표 수정

- src/common/components/layout/footer/footer.tsx
close #180 
- 사이드바 상태에 따라 푸터 너비 조절
isSidebarOpen 값을 추가로 검사하여 사이드바 상태에 따라 푸터 너비가 조절되도록 수정했습니다.
isSidebarOpen의 기본값이 true로 설정되어 있어 다른 페이지에서도 true로 인식되어, total-evaluation 페이지에서만 적용되도록 조건을 수정했습니다.
> [#180] - 사이드바 상태에 따른 푸터 너비 조절

- src/common/components/modal/base-modal.styles.ts
- src/common/components/toast/toast-config.tsx
- src/common/components/toast/toast.tsx
- src/features/profile/components/recent-feedback-modal/recent-feedback-modal.styles.ts
- src/features/profile/components/recent-feedback-modal/recent-feedback-modal.tsx
- src/features/upload/components/feedback-loading/loading-page-evaluation.styles.ts
- src/features/upload/components/feedback-loading/loading-top-section.tsx
close #175 
1. 히스토리 조회 모달에서 에러 UI 반영
2. 토스트 공통 컴포넌트에서 아이콘 이름이 아닌 아이콘 자체를 주입시키는 방법으로 변경
3. 디자인 QA에 따른 모달창 z-index 값 추가 및 세부 사항 수정
> [#175] - 히스토리 조회 모달 에러 UI 반영, 디자인 QA 반영

- src/common/components/layout/header-buttons/total-evaluation/total-evaluation-user-info.tsx
- src/features/feedback/services/use-get-portfolio-feedback.ts
- src/features/total-evaluation/utils/adapt-accordion-format.ts
- src/features/total-evaluation/utils/convert-kr-date.ts
close #186 
피드백 페이지에 사용되는 헤더의 메타데이터를 추가합니다.
- PDF 생성 날짜
- PDF 제목
현재 목데이터는 날짜값이 전부 `null`이므로 전부 `1970.01.01` 로 나오게 됩니다.
> [#186] - 피드백 헤더 메타 데이터 추가

- src/common/components/toast/toast-config.tsx
- src/features/total-evaluation/total-evaluation-page.styles.ts
- src/features/total-evaluation/total-evaluation-page.tsx
close #188 
- 포트폴리오 피드백 조회 에러 시 토스트 아이콘 수정
> [#188] - 포트폴리오 피드백 조회 에러 시 토스트 아이콘 수정

- src/common/components/feedback-state-observer/feedback-state-observer.tsx
- src/features/feedback/services/use-get-portfolio-feedback.ts
- src/features/total-evaluation/hooks/use-get-portfolio-feedback-data.ts
- src/features/upload/components/portfolio-upload/portfolio-upload.tsx
close #195 
- 피드백 요청 후 피드백 상세 조회할 때 fileId 대신 feedbackId를 사용하도록 수정했습니다.
- 파일 업로드 후 피드백 상세 조회 시 에러가 발생했던 이유는.. id를 다른 걸 넣어서 그런 거였습니다... 허허...
- 피드백 상세 조회 응답 데이터 변경에 따라 `UseGetPortfolioFeedbackResponse` 응답 타입을 수정했습니다.
```js
interface UseGetPortfolioFeedbackResponse {
feedback: {
createdAt: string;
updatedAt: string;
deletedAt: string;
id: string;
userId: string;
fileId: string;
title: string;
overallStatus: Status;
projectStatus: Status;
overallEvaluation: OverallEvaluationType;
additionalChat: AdditionalChatType[];
projectEvaluation: ProjectEvaluationType[];
};
imageList: string[];
}
```
@Limgabi 피드백 상세 조회 부분 타입을 수정했습니다. 해당 부분 확인 후 변경되어야 할 부분이 있다면 확인 부탁드립니다! 🙇
> [#195] - 피드백 상세 조회 응답 데이터 변경에 따른 대응

- src/features/feedback/services/use-get-feedback-history.ts
- src/features/profile/components/recent-feedback-modal/recent-feedback-modal-content.styles.ts
- src/features/profile/components/recent-feedback-modal/recent-feedback-modal-content.tsx
- src/features/profile/components/recent-feedback-modal/recent-feedback-modal.tsx
- src/features/upload/components/upload/upload.tsx
close #194 
1. 히스토리 조회 모달에서 기존에 테스트를 위해 userId 를 하드코딩했던 로직 제거
2. 히스토리 조회 모달에서 히스토리 클릭했을때 모달이 사라지지 않는 버그 수정
3. 히스토리 조회 모달에서 콘텐츠가 안넘쳐도 스크롤이 약간씩 되고 스크롤바가 있는 로직 수정
> [#194] - 히스토리 조회 모달 로직 수정

- src/features/feedback/services/use-get-feedback-history.ts
- src/features/upload/components/file-upload/file-upload.tsx
- src/features/upload/components/recent-feedback/recent-feedback.tsx
- src/features/upload/components/upload/upload.tsx
close #206 
- 최근 피드백 조회 API의 엔드포인트를 변경했습니다. `api/v1/feedback/recent/feedback` -> `api/v1/feedback/list`
- 다만 API에 서버측 이슈가 있어서 현재 수정중입니다. [슬랙](https://depromeet16th.slack.com/archives/C0878EM877X/p1743598259565219?thread_ts=1743585886.409229&cid=C0878EM877X)
- 파일 업로드 용량 제한을 5MB -> 50MB 로 변경했습니다.
- RecentFeedback 컴포넌트를 FallbackBoundary로 감쌌습니다.
- fallbackUI는 null로 설정했습니다. 최근 피드백이 없을 경우 UI가 없을 때에도 로딩 UI가 있을 경우 로딩 UI를 보여주다가 갑자기 사라지는 경험이 좋지 않을 것이라 판단해서 null 값으로 설정했습니다.
> [#206] - 피드백 페이지 API 호출 위치 수정 등

- src/common/components/layout/common-layout.styles.ts
- src/common/components/layout/common-layout.tsx
- src/common/components/layout/footer/footer.styles.ts
- src/common/constants/layout.ts
- src/features/landing/components/helpers-section/total-evaluation-grid.styles.ts
- src/features/login/login-page.styles.ts
- src/features/total-evaluation/total-evaluation-page.styles.ts
- src/features/upload/components/upload/upload.styles.ts
close #215 
- Layout 컴포넌트의 스타일을 변경했습니다.
전체 레이아웃을 flex 레이아웃으로 변경하고 Outlet을 감싼 div가 남은 영역을 차지하도록 수정했습니다.
기존 페이지 컴포넌트에 적용되어 있던 height 속성을 제거했습니다.
- total-evaludation-grid에서 사용한 nth-child 속성을 nth-of-type으로 변경했습니다.
- nth-child의 경우 부모 요소 기준 몇 번째 자식인지 판별하고, nth-of-type의 경우 부모 요소 기준 해당 선택자가 적용된 태그 요소 중 몇 번째인지 판별합니다. SSR의 경우 style 태그가 추가될 때 nth-child는 의도한 대로 동작하지 않기 때문에 오류를 출력한다고 합니다. [참고한 글](https://velog.io/@leehyunho2001/Next.jsSSR%EC%97%90%EC%84%9C-nth-child-%EA%B2%BD%EA%B3%A0)
@Limgabi 푸터 관련 작업하시면서 수정한 코드를 제가 다시 수정하게 되었습니다! 확인 한 번 부탁드립니다 🙇
> [#215] - Layout 스타일 변경 및 페이지 높이 값 제거

- src/features/landing/components/helpers-section/projects-wrapper.tsx
close #216
- scrollTrigger start 조건을 수정했습니다. trigger 요소의 center 기준 위로 56px 만큼 떨어진 지점이 시작점이 됩니다.
> [#216] - scrollTrigger start 조건 수정

- src/common/utils/scroll-to-section.ts
- src/features/landing/components/helpers-section/projects-wrapper.styles.ts
- src/features/landing/components/helpers-section/projects-wrapper.tsx
close #219
- useGsap 내부 pin 관련 설정을 수정했습니다.
기존에는 #landing-container를 pin 설정해주고 있었는데 해당 코드 때문에 레이아웃 시프트가 발생하는 걸로 확인했습니다.
아직 저도 gsap 라이브러리에 대한 이해가 부족하다보니 설명이 애매한 점 양해해주세요 ㅠㅠ 추후 공부해서 정리하고 공유드리겠습니다!
- gsap 설정을 수정한 후 FadeInWrapper가 동작하지 않는 문제가 있어 FadeInWrapper의 위계를 수정했습니다.
위계 수정에 따라 스타일도 일부 수정했습니다.
- gsap 설정을 수정하면서 상단 헤더의 help 버튼 클릭 시 이동해야할 y 값을 변경했습니다.
https://github.com/user-attachments/assets/649ee68f-7044-4863-9c05-00aa533e9364
로컬에서 빌드 후 테스트 해본 영상입니다. 초반에 깜빡이는 건 새로고침 하고 있는 건데 레이아웃 시프트가 발생하진 않았습니다.
> [#219] - 랜딩 페이지 레이아웃 시프트 수정(gsap 설정 수정)

- index.html
- src/features/upload/components/file-upload/file-upload.styles.ts
- src/features/upload/components/file-upload/file-upload.tsx
- src/features/upload/components/portfolio-upload/portfolio-upload.tsx
- src/features/upload/services/mutations.ts
- src/features/upload/services/post-portfolio.ts
close #240
업로드 시 로딩 프로그레스바를 추가했습니다.
axios의 onUploadProgress를 사용했는데, 업로드 자체만 값을 가져올 수 있고 실제로 클라이언트에서 응답을 받았는지는 알 수 없어서 프로그레스바와 살제 호출 완료 시점에는 차이가 존재합니다.
타이틀명을 변경했습니다.
https://github.com/user-attachments/assets/91715c1f-c161-4e42-85cc-b0b7385aa3df
> [#240] - 업로드 시 로딩 프로그레스바 추가

- src/common/components/layout/header-buttons/profile-dropdown.tsx
- src/common/hooks/use-toast.ts
close #269
비로그인 상태일때 toast 제거
🗣 리뷰어에게 할 말 (선택)
- 아직 로그아웃후에 로그인하면 다시 풀링 api 보내는 로직이 없어 로그아웃 한 다음 로그인을 하면 다시 toast가 나오지 않습니다. 추후에 고쳐야 할 것 같습니다.
> [#269] -  비로그인 상태일때 toast 제거

- src/common/components/feedback-state-observer/feedback-state-observer.tsx
- src/common/components/global-route-config/global-route-config.tsx
- src/common/hooks/use-toast.ts
- src/features/landing/components/routing-section/routing-start-section.tsx
- src/features/upload/components/portfolio-upload/portfolio-upload.tsx
close #276
- 진행중인 피드백을 이메일 별로 관리하도록 수정했습니다.
- 로그아웃 하거나 다른 계정으로 로그인 했을 때 API 폴링을 하지 않기 위함입니다.
- 커밋을 쪼개지 못했는데, 에러가 발생했을 때 프로그레스 바를 보여주지 않도록 수정했습니다.
- toastType이 truthy일 경우 toastOpen 상태를 true로 설정하도록 수정했습니다.
- 토스트가 떴다가 사라지면 다음 토스트가 뜨지 않는 문제를 해결하기 위함입니다. toastOpen 상태에 따라 토스트를 보여주고 있는데, 초기 상태가 true이고 toast가 닫히면서 false로 변경되는데, 다음 토스트가 떠야할 시점에 toastOpen 상태를 true로 변경하지 않고 있기 때문에 토스트가 보이지 않는 버그가 있었습니다. 
https://github.com/user-attachments/assets/37ce31da-d11a-4547-b0d7-657b606dcf86
1. 업로드 에러 -> 업로드 에러 -> 피드백 시작 시 각 스텝마다 토스트가 잘 뜹니다.
2. 피드백 시작 후 로그아웃 시 피드백 진행중 토스트가 뜨지 않습니다.
> [#276] - 진행중인 피드백 id 저장 방식 변경
