.husky/commit-msg
#2 
- 이슈 번호 포함하도록 커밋 메시지 검증 스크립트 수정
=> [#2] - 커밋 메시지 검증 스크립트 수정

.gitignore, .storybook/main.ts, .storybook/preview.ts, package.json, pnpm-lock.yaml, script/publish_chromatic.sh, src/components/progress-bar/index.tsx, src/stories/Configure.mdx, src/stories/ProgressBar.stories.tsx
#1 
- Storybook 설정
- Chromatic 배포 스크립트 추가 및 프로젝트 토큰 환경변수로 관리
- ProgressBar 컴포넌트 구현 후 Storybook 예제 작성 (예제 작성을 위한 임시 컴포넌트)
=> [#1] - Storybook 설정 및 배포

.github/WORKFLOWS/deploy.yml
=> chore #5 : CI 세팅

.github/workflows/deploy.yml
#5
> CI 세팅 fix
> 관련 스크린샷을 첨부해 주세요.
> 집중적으로 리뷰받고 싶은 부분이 있다면 적어 주세요.
=> chore #5 : CI 세팅 fix

.github/workflows/chromatic.yml, src/stories/ProgressBar.stories.tsx
close #22 
- Storybook CI/CD 파이프라인 구축
=> [#22] - Storybook CI/CD 파이프라인 구축

src/App.tsx, src/styles/globalStyles.ts
close #31 
- Reset CSS를 적용하고, 기본 단위를 rem으로 설정하기 위해 html의 font-size를 변경했습니다.
- px을 rem으로 쉽게 변환할 수 있도록 font-size를 조정했습니다.
=> [#31] - Reset CSS 적용 및 기본 단위 rem으로 설정

src/assets/styles/colors.ts
=> [#71] - Colorsystem 추가

package.json, pnpm-lock.yaml, src/app.tsx
close #102 
Tanstack-query 데브툴즈 적용
=> [#102] - Tanstack-query 데브툴즈 적용

src/common/components/auth/Authorization.tsx
close #117 
로그인 리다이렉션 로직을 제거 합니다.
=> [#117] - 로그인 리다이렉션 로직 제거

src/common/components/layout/common-layout.styles.ts
close #133 
공통 레이아웃에 스크롤 제한 요소를 제거 합니다
```
overflow-y: auto;
overscroll-behavior-y: contain;
```
=> [#133] - 공통 레이아웃 스크롤 제한 요소 제거

src/assets/styles/device-width.ts, src/common/hooks/use-device-type.ts, src/features/upload/components/feedback-loading/loading-page-evaluation.styles.ts, src/features/upload/components/feedback-loading/loading-page-evaluation.tsx
close #140 
1. 반응형 SIze 수정
2. 수정에 따른 코드 변경
=> [#140] - 반응형 Size 수정

src/common/components/layout/header-navigation/header-navigation-layout.styles.ts, src/common/components/layout/header-navigation/header-navigation-layout.tsx, src/common/hooks/use-header-contents.tsx, src/features/upload/components/feedback-loading/loading-project-evaluation.tsx, src/features/upload/components/feedback-loading/loading-title.tsx, src/features/upload/components/feedback-loading/loading-top-section.styles.ts, src/features/upload/components/feedback-loading/loading-top-section.tsx, src/features/upload/components/feedback-loading/loading-total-evaluation.tsx, src/features/upload/constants/loading-constant.ts
close #151 
1. 이미지 위치 변경으로 인한 경로 수정
2. Header에 Loading 페이지 추가
3. 포트폴리오 피드백 인터렉션 일부 적용
fade-in-div 개선으로 인해 인터렉션 일부만 적용하고 개선 되면 다시 적용하겠습니다..!
=> [#151] - 경로 수정, Header 오류 수정, 포트폴리오 피드백 인터렉션 일부 적용

src/common/hooks/use-shadow-scroll.tsx, src/features/feedback-history/services/use-get-feedback-history.ts, src/features/profile/components/recent-feedback-modal/recent-feedback-modal.styles.ts, src/features/profile/components/recent-feedback-modal/recent-feedback-modal.tsx, src/features/total-evaluation/components/project-evaluation/project-evaluation.tsx, src/features/upload/components/feedback-loading/loading-page-evaluation.styles.ts, src/features/upload/components/feedback-loading/loading-page-evaluation.tsx, src/features/upload/components/feedback-loading/loading-top-section.tsx, src/features/upload/constants/loading-constant.ts, src/features/upload/upload-page.tsx
close #154 
1. 이미지 경로로 인해 배포과정에서 이미지가 안나오던 문제 수정
2. 특정 요소의 스크롤이 상하좌우 끝에 도달했는지 감지하는 커스텀 훅 구현
3. 피드백 로딩 화면 모바일 뷰에 가로 스크롤 생기는 부분에 그림자 스타일 적용
4. modal 로직 일부 수정
https://github.com/user-attachments/assets/4ed6c6a3-c131-47a6-b729-cac3a3b17c33
- 현재 그림자 세부 스타일이 안나와서 임시로 적용해두었습니다..! 그림자 스타일 나오면 바꾸겠습니다..!
=> [#154] - 가로 스크롤 그림자 스타일 적용

src/features/upload/components/feedback-loading/loading-evaluation-bottom.tsx, src/features/upload/components/feedback-loading/loading-page-evaluation.tsx, src/features/upload/components/feedback-loading/loading-project-evaluation.tsx, src/features/upload/components/feedback-loading/loading-title.styles.ts, src/features/upload/components/feedback-loading/loading-title.tsx, src/features/upload/components/feedback-loading/loading-top-section.styles.ts, src/features/upload/components/feedback-loading/loading-top-section.tsx, src/features/upload/components/feedback-loading/loading-total-evaluation.tsx
close #160 
피드백 로딩 페이지 FadeInWrapper 를 활용하여 인터렉션 적용
영상을 올리고 싶은데 용량이 커서 못올려요 ㅜㅜ
=> [#160] - 피드백 로딩 페이지 인터렉션 적용

src/features/landing/components/frequently-asked-questions/frequently-asked-questions.styles.ts, src/features/landing/components/frequently-asked-questions/frequently-asked-questions.tsx, src/features/landing/components/helpers-section/detail-improvement.styles.ts, src/features/landing/components/helpers-section/detail-improvement.tsx, src/features/landing/landing-page.styles.ts, src/features/landing/landing-page.tsx
close #150 
- 랜딩 페이지 디자인 QA 반영 (세부 개선점, 자주 묻는 질문)
=> [#150] - 랜딩 페이지 디자인 QA 반영

src/common/components/layout/footer/footer.tsx
close #182 
사이드바 context 타입 및 import문을 수정합니다.
이전에 사이드바의 createContext 초깃값을 제거하고, Provider 내부에 사용하는걸 강제하고자 사용 패턴을 일부 수정했었는데 이로 인해 발생한 import문을 수정합니다.
=> [#182] - 사이드바 context 타입 및 import 수정

src/features/landing/components/helpers-section/detail-improvement.styles.ts
close #190 
- 랜딩 페이지 세부 개선점 shadow 수정
=> [#190] - 랜딩 페이지 세부 개선점 shadow 수정

src/common/components/layout/header-buttons/auth-profile-modal-dropdown.tsx, src/common/components/layout/header-buttons/total-evaluation/total-evaluation-user-info.tsx, src/common/utils/get-value-or-hyphen.ts, src/features/feedback/services/use-get-portfolio-feedback.ts, src/features/total-evaluation/components/accordion-list/feedback-contents.tsx, src/features/total-evaluation/components/nested-list/nested-list.tsx, src/features/total-evaluation/components/overall-evaluation/overall-evaluation.tsx, src/features/total-evaluation/components/project-evaluation/project-evaluation-list.tsx, src/features/upload/components/file-upload/file-upload.tsx
close #198 
- 값이 없을 경우 '-'을 반환하는 유틸 함수 구현
- UseGetPortfolioFeedbackResponse 타입 수정 및 value 빈 배열일 경우 예외처리
=> [#198] - 값이 없을 경우 '-'을 반환하는 유틸 함수 구현

.github/workflows/deploy.yml
close #210 
배포 워크플로 파일에서 vars 대신 secrets를 사용하도록 변경했습니다.
=> [#210] - vars -> secrets로 변경

src/common/components/fallback-boundary/fallback-boundary.tsx, src/features/feedback/services/use-get-portfolio-feedback.ts
close #213 
- FallbackBoundary reset 시 Query 상태도 초기화되도록 개선
=> [#213] - FallbackBoundary reset 시 Query 상태도 초기화되도록 개선

src/assets/styles/global-styles.ts
close #223 
- font-synthesis: none 속성을 추가해 폰트 합성을 방지합니다. [참고한 글](https://velog.io/@duddlfkd02/%ED%94%84%EB%A6%AC%ED%85%90%EB%8B%A4%EB%93%9C-%ED%8F%B0%ED%8A%B8%EA%B0%80-%EC%82%AC%ED%8C%8C%EB%A6%AC%EC%97%90%EC%84%9C%EB%8A%94-%EC%A0%81%EC%9A%A9%EC%9D%B4-%EC%9D%B4%EC%83%81%ED%95%98%EB%8B%A4..-font-synthesis-%ED%8F%B0%ED%8A%B8-%ED%95%A9%EC%84%B1-%EB%AC%B8%EC%A0%9C)
=> [#223] - font-systhesis: none 속성 추가

src/common/components/layout/header-buttons/auth-profile.styles.ts, src/common/components/layout/header-buttons/auth-profile.tsx, src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.styles.ts, src/features/total-evaluation/components/feedback-sidebar/feedback-sidebar.tsx
close #229 
- 구글 프로필 이미지가 null값으로 내려올 때 보여줄 fallback UI 생성
- 프로젝트 이름이 사이드바 길이를 초과할 경우 말줄임표(ellipsis) 표기
=> [#229] - 더미 프로필 추가, 사이드바 텍스트 초과 처리 

src/common/components/layout/footer/footer.styles.ts, src/common/components/layout/footer/footer.tsx, src/features/total-evaluation/components/evaluation-table/evaluation-table.styles.ts, src/features/total-evaluation/components/overall-evaluation/overall-evaluation.tsx, src/features/total-evaluation/components/project-evaluation/project-evaluation.tsx, src/features/upload/components/upload/upload.tsx
close #232 
- 랜딩페이지 및 포트폴리오 피드백 조회 QA 반영
=> [#232] - 랜딩페이지 및 포트폴리오 피드백 조회 QA 반영

src/assets/icons/not-found.svg, src/common/components/not-found-page/not-found-page.styles.ts, src/common/components/not-found-page/not-found-page.tsx, src/common/types/icon-types.ts, src/route.tsx
close #이슈번호
404 page 추가
router 에서 저런 방식으로 404 페이지를 추가하는게 맞는지 확인 한번 부탁드립니다..!
=> Feat 404page

src/common/components/layout/footer/footer.styles.ts, src/common/components/layout/footer/footer.tsx, src/common/stories/dummy-data/sidebar.ts, src/features/feedback/services/use-get-portfolio-feedback.ts, src/features/total-evaluation/components/project-evaluation/project-evaluation.tsx
close #238
- 포트폴리오 피드백 조회 응답값 수정
=> [#238] - 포트폴리오 피드백 조회 응답값 수정

src/common/components/layout/header-buttons/profile-dropdown.styles.ts, src/common/components/layout/header-buttons/total-evaluation/single-profile-modal-button.styles.ts, src/common/components/layout/header-navigation/header-navigation-layout.styles.ts, src/features/landing/components/helpers-section/total-evaluation-grid.styles.ts, src/features/total-evaluation/components/custom-buttons/add-button.tsx, src/features/total-evaluation/components/sidebar/base-sidebar-left/base-sidebar-left.styles.ts, src/features/total-evaluation/components/sidebar/feedback-page-navigator/control-buttons.styles.ts, src/features/total-evaluation/components/sidebar/feedback-page-navigator/control-buttons.tsx, src/features/total-evaluation/hooks/use-get-portfolio-feedback-data.ts
close #233 
- 사이드바 '+' 버튼 클릭시 업로드 페이지 이동
- 헤더 z-index 수정
- 피드백 데이터에서 페이지 뒤에 붙는 확장자 제거
- 헤더 모달 스토리 조회 색상 및 radius 변경
- 랜딩 페이지 문장 간 간격 수정
=> [#233] - QA: 헤더, 사이드바, 랜딩 페이지

src/assets/styles/global-styles.ts
=> [#242] - font 범위 설정

src/assets/styles/global-styles.ts
=> [#242] - font synthesis 제거

src/common/components/toast/toast.styles.ts
=> [#247] - toast 너비 지정

src/features/total-evaluation/components/project-evaluation/project-evaluation.tsx, src/features/total-evaluation/total-evaluation-page.styles.ts
close #251 
- 포트폴리오 피드백 조회 스타일 수정 (한 줄 요약 Spacing 제거)
=> [#251] - 포트폴리오 피드백 조회 스타일 수정 (한 줄 요약 Spacing 제거)

src/features/login/components/custom-buttons/google-auth-button.styles.ts, src/features/login/components/custom-buttons/google-auth-button.tsx, src/features/login/components/mobile-view.styles.ts, src/features/login/components/mobile-view.tsx
=> [#258] - 로그인 페이지 모바일 뷰

src/common/components/feedback-state-observer/feedback-state-observer.tsx
close #259
> 주요 변경 사항을 작성해 주세요.
> 관련 스크린샷을 첨부해 주세요.
> 집중적으로 리뷰받고 싶은 부분이 있다면 적어 주세요.
=> fix #259 : 피드백 완료 시 IDLE 상태로 수정

src/features/upload/services/mutations.ts
=> [#263] - 허용 계정 추가

src/common/components/feedback-state-observer/feedback-state-observer.tsx, src/features/landing/components/helpers-section/total-evaluation-grid.tsx, src/features/upload/components/feedback-loading/loading-project-evaluation.tsx, src/features/upload/components/feedback-loading/loading-total-evaluation.tsx
close #이슈번호
> 주요 변경 사항을 작성해 주세요.
> 관련 스크린샷을 첨부해 주세요.
> 집중적으로 리뷰받고 싶은 부분이 있다면 적어 주세요.
=> Fix feedback state

src/features/upload/components/portfolio-upload/portfolio-upload.tsx, src/features/upload/services/mutations.ts
=> [#270] - 정적 계정 허용 리스트 제거

package.json, script/generate-image-url.ts, src/common/constants/images.ts
close #279
1. package.json에서 이미지 경로 파싱 스크립트 코드 ts로 인해 npx tsx 붙여주기
2. 이미지 경로 파싱하는 스크립트 코드 수정
=> [#279] - 버셀에서 이미지 못 불러오는 버그 수정

src/common/components/toast/toast-config.tsx, src/common/components/toast/toast.styles.ts, src/common/hooks/use-toast.ts, src/features/upload/components/feedback-loading/loading-page-evaluation.tsx, src/features/upload/components/portfolio-upload/portfolio-upload.tsx, src/features/upload/constants/loading-constant.ts, src/store/feedback.ts
close #283
1. 디자이너 포트폴리오만 업로드 가능하다고 알려주는 토스트 추가
2. 포트폴리오 업로드 로딩 화면에서의 이미지 경로 수정
=> [#283] - 디자이너 포트폴리오만 업로드 가능하다고 알려주는 토스트 추가

src/features/upload/components/bar-chart/bar-chart.styles.ts, src/features/upload/components/bar-chart/bar-chart.tsx, src/features/upload/components/feedback-loading/loading-top-section.tsx, src/features/upload/components/file-upload/file-upload.tsx
close #290 
- 로딩 화면 문구 변경
- 업로드 프로그레스바 수정
=> [Refactor] 로딩 화면 타이틀 수정 및 업로드 프로그레스바 수정

src/common/components/icon/icon.tsx, src/common/components/layout/footer/footer.tsx
=> [#293] - Behance 링크 추가

src/common/components/layout/common-layout.styles.ts, src/common/components/layout/header-buttons/profile-dropdown.styles.ts, src/common/components/layout/header-navigation/header-navigation-layout.styles.ts, src/common/components/toast/toast.styles.ts, src/common/constants/z-index.ts, src/common/hooks/use-get-modal-z-index.ts, src/features/landing/components/helpers-section/detail-improvement.styles.ts, src/features/profile/components/recent-feedback-modal/recent-feedback-modal-content.styles.ts, src/features/total-evaluation/components/custom-buttons/page-location-button.styles.ts, src/features/total-evaluation/components/project-evaluation/project-evaluation.styles.ts, src/features/total-evaluation/components/sidebar/base-sidebar-left/base-sidebar-left.styles.ts, src/features/upload/components/feedback-loading/loading-page-evaluation.styles.ts
close #295 
- z-index 상수로 분리
z-index 값들을 상수로 분리했습니다. 인덱스 순서가 중요하지 않다면 기본값을 적용하였습니다. 변경된 부분에서 z-index 값을 수정하고 싶으시면 자유롭게 하셔도 될 거 같아요!
=> [#295] - z-index 상수로 분리

src/common/constants/z-index.ts
close #298 
- 헤더 및 사이드바 z-index 변경
=> [#298] - 헤더 및 사이드바 z-index 변경
